---
bibliography: references.bib
editor:
    markdown: 
      wrap: sentence
---

# Requirements

<!-- 
An idea of what is required to make the project actually happen
-->

## People

Nicholas Tierney and Eric Scott will take the lead in developing code for this project.
Both have experience developing R packages and working with `targets` as well as some experience with geospatial analysis in R.
Additionally we plan to consult with geospatial experts who are more familiar with the "rough edges" related to doing geospatial analysis in R and with the `targets` package.

## Processes

<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

We will adopt a code of conduct and contribution guideline based on guidelines used by rOpenSci.
Communication regarding development will happen primarily via GitHub issues, with additional communication not regarding code happening via the rOpenSci Slack where both Eric and Nicholas are members.
We may hold occasional video meetings as well.

## Funding

We request funding to pay for the time of the personnel working on this project.

-   Eric Scott, 108 hours totaling \$5,045
-   Nicholas Tierney, 108 hours totaling \$7,128

Additionally, we will consult with geospatial experts and would like to be able to pay them for their time:

-   Consulting, 36 hours totaling \$3600

For a total of: \$15773

**Funding timeline**

-   After milestone 1 (July 31): \$5257.67 <!--# third? -->
-   After milestone 2 (September 30): \$5257.67 <!--# third? -->
-   After technical delivery (November 30): \$5257.67 <!--# the rest -->

## Summary

<!--
A summary of the requirements that contextualises the costs
-->

These costs are a one-time investment to pay for initial development of the `geotargets` package totaling \$15773.
