---
bibliography: references.bib
editor:
    markdown: 
      wrap: sentence
---

# Project plan

## Start-up phase

<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

We already have created a [repository](https://github.com/njtierney/geotargets) on GitHub with a bare-bones package with GitHub actions being used to run package checks.
In the start-up phase, we will focus on making design decisions about what the package will offer.
For example, will we provide alternatives to `targets::tar_target()` the way the `tarchetypes` package does (e.g. `tarchetypes::tar_url()`), or will we simply provide `format_*` objects to use in the `format` argument of `tar_target()`?
What r-spatial packages will we support and what are their relative priorities?
What file types will we support as storage formats for targets?
Answering these questions will lay the groundwork for efficient collaborative development of the package.

## Technical delivery

<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

Our goal is to deliver a package that allows users to use the `targets` package with various r-spatial packages (`terra`, `sf`, `stars`, etc.) with as little friction as possible.

Milestone 1: <date>

-   Basic package with functionality for `terra` raster and vector objects
-   Well documented functions with high test coverage ensuring a solid start to the project
-   Creation of a `pkgdown` website for the package hosted on GitHub pages

Milestone 2: <date>

-   Add support for objects from a second r-spatial package -Benchmarking of various file type options for storing targets including file size and read and write speed

Milestone 3: <date>

-   Add support for objects from a third r-spatial package

## Other aspects

<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

Throughout the project we will seek feedback from users on social media (Mastodon and Twitter) and on the `targets` discussion forum.
Each milestone will coincide roughly with a release on GitHub and a short blog post on https://www.njtierney.com/
